services:
  - type: web
    name: frontend
    env: docker
    repo: https://github.com/sakshisinha-13/CPlayground
    dockerContext: client
    dockerfilePath: client/Dockerfile
    plan: free
    envVars:
      - key: REACT_APP_API_BASE
        value: dummy
      - key: COMPILER_API
        value: dummy

  - type: web
    name: backend
    env: docker
    repo: https://github.com/sakshisinha-13/CPlayground
    dockerContext: server
    dockerfilePath: server/Dockerfile
    plan: free
    envVars:
      - key: MONGO_URI
        value: dummy
      - key: JWT_SECRET
        value: dummy

  - type: web
    name: compiler
    env: docker
    repo: https://github.com/sakshisinha-13/CPlayground
    dockerContext: compiler
    dockerfilePath: compiler/Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: "8000"
      - key: GEMINI_API_KEY
        value: dummy
