services:
  - type: web
    name: frontend
    env: docker
    repo: https://github.com/sakshisinha-13/CPlayground
    dockerContext: ./client
    plan: free
    envVars:
      - key: REACT_APP_API_BASE
      - key: COMPILER_API

  - type: web
    name: backend
    env: docker
    repo: https://github.com/sakshisinha-13/CPlayground
    dockerContext: ./server
    plan: free
    envVars:
      - key: MONGO_URI
      - key: JWT_SECRET

  - type: web
    name: compiler
    env: docker
    repo: https://github.com/sakshisinha-13/CPlayground
    dockerContext: ./compiler
    plan: free
    envVars:
      - key: PORT
      - key: GEMINI_API_KEY
