services:
  - type: web
    name: frontend
    env: docker
    repo: https://github.com/sakshisinha-13/CPlayground
    dockerContext: ./client
    plan: free
    envVars:
      - key: REACT_APP_API_BASE
        value: http://backend:5000
      - key: COMPILER_API
        value: http://compiler:8000/run

  - type: web
    name: backend
    env: docker
    repo: https://github.com/sakshisinha-13/CPlayground
    dockerContext: ./server
    plan: free
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://Sakshi:sakshi123@cluster0.oza1zcj.mongodb.net/codeplayground?retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        value: algouni-secret

  - type: web
    name: compiler
    env: docker
    repo: https://github.com/sakshisinha-13/CPlayground
    dockerContext: ./compiler
    plan: free
    envVars:
      - key: PORT
        value: 8000
      - key: GEMINI_API_KEY
        value: AIzaSyATS1hr0ehu4RPCCWO5AReSVOebhWP5ZGc
